apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sherlock.fullname" . }}
  labels:
    {{- include "sherlock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sherlock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sherlock.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sherlock.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "sherlock.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ include "sherlock.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/textquery/config
              name: config-volume
            - mountPath: /etc/textquery/secret
              name: secret-volume
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sherlock.fullname" . }}
                  key: password
          args:
            - serve
            - --config
            - /etc/textquery/config/config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        {{- if .Values.enableTunnelService }}
        - name: "tunnel"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: cloudflare/cloudflared:2022.6.3
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - tunnel
            - --no-autoupdate
            - --loglevel
            - debug
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "sherlock.fullname" . }}
                  key: tunnel_token
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
